name: Run Playwright Script

on:
  workflow_dispatch:   # manual run
  push:                # run when code pushed
  schedule:
    - cron: "30 9 * * *"   # runs daily at 09:30 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Playwright browsers
          python -m playwright install

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json
          python my_script.py
