steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
        python-version: "3.11"

  - name: Cache pip
    uses: actions/cache@v4
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Install Playwright browsers
    run: |
      python -m playwright install --with-deps chromium

  # Optional: Show disk and env context (for debugging)
  - name: Env context
    run: |
      python -V
      which python
      pip -V

  - name: Run scraper (attempt 1)
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    run: |
      set -e
      python main.py

  # Optional automatic retry once if it fails due to transient issues
  - name: Retry on failure (attempt 2)
    if: failure()
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    run: |
      echo "Retrying after 60s..."
      sleep 60
      python main.py