name: Sales With Action

on:
  # Manual run
  workflow_dispatch: {}
  # Scheduled daily run at 07:05 UTC (adjust as needed)
  schedule:
    - cron: "30 14 * * *"

permissions:
  contents: read

jobs:
  test_credentials:
    name: Test Google Auth
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run credential test
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "▶ Verifying Google Sheets credentials..."
          python test_google_auth.py

  scrape_foreclosures:
    name: Scrape Foreclosure Sales
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [test_credentials]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run scraper (attempt 1)
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          # Optional: tune your scraper via env if you add flags
          # POLITE_DELAY_SECONDS: "1.5"
        run: |
          echo "▶ Running foreclosure scraper..."
          python main.py

      - name: Retry on failure (attempt 2
